### PR TITLE
Refactor `build.py` and add GitHub Actions CI

### PR DESCRIPTION
**Pull request by disposedtrolley**
Hello!

I'm very happy to see some open source work being done in FS2020. I'm still working my way through the SDK docs and getting familiar with this project, so in the meantime I thought it might be nice to add a CI system.

This PR adds a few things:

- A GitHub Actions workflow with a single `CI` job. This will execute on every pull request and any pushes/merges into `master`. Right now, this verifies that `build.py` has been run before a PR can be merged.
- Refactors the `build.py` to move some of the logic into separate functions.
- Modifies `build.py` to sort `layout.json` alphabetically so we get a consistent result regardless of any Python version or OS inconsistencies.

Let me know your thoughts! And thanks for open sourcing this project :D

### CODE REVIEW

**Comment by arvinjarvin** [comment]
Hello.

Please add
`if rel_file.split('\\')[0] == '.git':
                continue `

Before line 20 of build.py, so that files in the git working directory are not added to the layout.

**Review by arvinjarvin — CHANGES_REQUESTED** [review]
As commented, build.py

**Comment by disposedtrolley** [comment]
> Please add
> `if rel_file.split('\\')[0] == '.git': continue `
> 
> Before line 20 of build.py, so that files in the git working directory are not added to the layout.

Since the build script is always being run in the `A32NX` folder, I don't think we'd need to worry about ignoring Git files since those would reside in the root directory.

I might take this opportunity to move `build.py` into its own `scripts` folder, and touch up the README to specify where it should be run. What do you think?

**Comment by wpine215** [comment]
Can we test this out on the dev branch first instead of master?

**Review by arvinjarvin — APPROVED** [review]

**Comment by disposedtrolley** [comment]
@wpine215 @arvinjarvin do you mind checking if Actions are enabled in the repo settings? It didn't seem to execute when this PR was merged into master, nor for some PRs opened recently.

**Comment by michaeldiguiseppi** [comment]
hey buddy, @disposedtrolley it seems that in order to make the check layout.json function, the CI has to have access to other people's remote forks, and i think thats where its getting hung up on permissions. We're getting failures due to permission denied. Can you take a look, or see if theres any way around this?

**Comment by disposedtrolley** [comment]
@michaeldiguiseppi my bad! I didn't make the bash script executable in this PR. I'll open up another PR in a sec!

**Comment by disposedtrolley** [comment]
@michaeldiguiseppi fixed in https://github.com/wpine215/msfs-a320neo/pull/178

sorry about that!

**Comment by michaeldiguiseppi** [comment]
@disposedtrolley no worries! Thanks for the quick fix!

**Pull request merged**
