### PR TITLE
Changed minimum brightness to 0 on all displays

### PR DESCRIPTION
**Pull request by topiek-fs**
Fixes issue #334 and #165

### CODE REVIEW

**Comment by JackZ974** [comment]
Hmmm. Not sure that this will really solve the issue. 
Actually turning the brightness knob all the way counterclockwise should turn the display OFF, not simply blank it.

**Comment by AdenFlorian** [comment]
> 
> 
> Hmmm. Not sure that this will really solve the issue.
> Actually turning the brightness knob all the way counterclockwise should turn the display OFF, not simply blank it.

What's the difference from the user's perspective?

**Comment by nistei** [comment]
> What's the difference from the user's perspective?

The displays should perform a self test after being powered on again. See #332

**Comment by topiek-fs** [comment]
Screenshots:

**Before:**
afbeelding
afbeelding

**After:**
afbeelding
afbeelding

**Comment by AdenFlorian** [comment]
> 
> 
> > What's the difference from the user's perspective?
> 
> The displays should perform a self test after being powered on again. See #332

👍 I think it's fine for this PR to still be merged as is and a different PR can address the self test.
or @topiek-fs can add that to this PR if they want.

**Comment by topiek-fs** [comment]
> 
> 
> > What's the difference from the user's perspective?
> 
> The displays should perform a self test after being powered on again. See #332

I would've thought this is logic would be handled in JavaScript? As the selftest div defaults to on, and after X seconds it goes sets the display to none. So my guess was the javascript monitors the brightness knob value, and if it changes from 0, you reïnstate the selftest div.

**Comment by AdenFlorian** [comment]
> 
> 
> > > What's the difference from the user's perspective?
> > 
> > 
> > The displays should perform a self test after being powered on again. See #332
> 
> I would've thought this is logic would be handled in JavaScript? As the selftest div defaults to on, and after X seconds it goes sets the display to none. So my guess was the javascript monitors the brightness knob value, and if it changes from 0, you show the selftest div.

did it show the self test when you tested it after turning the brightness to 0 then back on again?

**Comment by topiek-fs** [comment]
> 
> 
> > > > What's the difference from the user's perspective?
> > > 
> > > 
> > > The displays should perform a self test after being powered on again. See #332
> > 
> > 
> > I would've thought this is logic would be handled in JavaScript? As the selftest div defaults to on, and after X seconds it goes sets the display to none. So my guess was the javascript monitors the brightness knob value, and if it changes from 0, you show the selftest div.
> 
> did it show the self test when you tested it after turning the brightness to 0 then back on again?

No, because I don't think that logic is in the javascript files for the panels. The panels simply show selftest on startup, theres no additional logic for turning it on AFAIK.

**Comment by AdenFlorian** [comment]
> 
> No, because I don't think that logic is in the javascript files for the panels. The panels simply show selftest on startup, theres no additional logic for turning it on AFAIK.

Ok, then yea, changes still need to be made to fix #332, which could be done in this or a new PR IMO

**Comment by topiek-fs** [comment]
> 
> 
> > No, because I don't think that logic is in the javascript files for the panels. The panels simply show selftest on startup, theres no additional logic for turning it on AFAIK.
> 
> Ok, then yea, changes still need to be made to fix #332, which could be done in this or a new PR IMO

I was originally going to look into that until I saw that it actually doesn't turn off at all. I'll look into it!

**Comment by Curtis-VL** [comment]
Yeahhhh, implementing self-test on them re-enabling should be another PR. 👍

**Pull request merged**
