### PR TITLE
Add "range change" message & tweak "mode change" message

### PR DESCRIPTION
**Pull request by FarukEroglu2048**

### CODE REVIEW

**Comment by FarukEroglu2048** [comment]
I was unable to revert to old layout.json without breaking things, so I'm leaving it to project maintainers.

**Comment by noga-aviator** [comment]
everything tested in sim ?

**Comment by noga-aviator** [comment]
pls resolve the conflict on the html

**Comment by FarukEroglu2048** [comment]
Yes, works just fine

**Comment by noga-aviator** [comment]
can you resolve the confict on the html file

**Pull request merged**
