### PR TITLE
Added new automatic ECAM page switch 

### PR DESCRIPTION
**Pull request by noga-aviator**
Added the fact that DOOR page is displayed when engine are off
Added the fact that when apu is started without the external power runing, the apu page will display for 10 second and then be replaced by the DOOR page

### CODE REVIEW

**Comment by noga-aviator** [comment]
also fixed a bug where gen info weren't displayed when apu master was on

**Comment by noga-aviator** [comment]
also pls don't merge the readme

**Comment by wpine215** [comment]
Also I recommend waiting until somebody tests this branch in the simulator before merging to dev, since a QA test hasn't been done yet.

**Comment by michaeldiguiseppi** [comment]
I was going to pull it down to test but its showing its from an unknown repository.

**Comment by wpine215** [comment]
Sounds like he made his fork (where the changes are) private, so we'll have to wait for him to come online again to fix and test it.

**Comment by fspijkerman** [comment]
@michaeldiguiseppi In case you don't want to wait, it's possible to do this without the remote fork/branch
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally

**Comment by noga-aviator** [comment]
ahhhh, yes sorry, i thought the PR was closed.
I'm going to test that out in sim and reupload everything !

**Pull request closed without merging**
