### PR TITLE
Fixed taxi light bleeding into the cockpit

### PR DESCRIPTION
**Pull request by ThePilot916**

### CODE REVIEW

**Comment by LorDawid** [comment]
It still lights up the cockpit in taxi position.

**Comment by ThePilot916** [comment]
> It still lights up the cockpit in taxi position.

I've checked it, and it did not. You sure you have the effects folder and layout.json updated? 

You should download the files from my dev branch and not the one here since it hasn't been merged yet.

**Comment by LorDawid** [comment]
Sorry, my fault, I thought it was already merged

**Comment by aboodilatif** [comment]
works, tooltip to show switch pos

image

**Pull request merged**
